version: '3.9'
services:
  db:
    image: mysql
    container_name: 'financial-control-db'
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
    ports:
      - '3306:3306'
    volumes:
      - 'fcdb-vol:/var/lib/mysql'
    deploy:
      restart_policy:
        condition: 'on-failure'
        max_attempts: 3
        delay: '5s'
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'
        reservations:
          memory: '128M'
          cpus: '0.2'

volumes:
  fcdb-vol:
