spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/financial-control?serverTimezone=UTC'
    username: 'root'
    password: '12345'

    hikari:
      maximum-pool-size: 12
      minimum-idle: 4
      max-lifetime: 30000

  jpa:
    generete-ddl: false

  flyway:
    locations: [classpath:db/migration, classpath:db/callback]

logging:
  level:
    org.hibernate.SQL: DEBUG